sudo: required
services:
  - docker

before_install:
  - docker build -t nazuzarte/react-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run -e CI=true nazuzarte/react-test npm test

after_success:
  - docker build -t nazuzarte/multi-client ./client
  - docker build -t nazuzarte/multi-nginx ./nginx
  - docker build -t nazuzarte/multi-server ./server
  - docker build -t nazuzarte/multi-worker ./worker

  #Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to docker hub
  - docker push nazuzarte/multi-client
  - docker push nazuzarte/multi-nginx
  - docker push nazuzarte/multi-server
  - docker push nazuzarte/multi-worker